"""Hermes tool schemas for Nerve v0.3.1rc1."""

NERVE_DECIDE={"name":"nerve_decide","description":"Make one bounded typed decision through the configured Reflex backend.","parameters":{"type":"object","properties":{"state":{},"instructions":{"type":"string"},"choices":{"type":"array","items":{"type":"string"},"minItems":2},"criteria":{"type":"object","additionalProperties":{}},"contract":{"type":"string"}},"required":["state","instructions","choices"]}}
NERVE_RANK={"name":"nerve_rank","description":"Rank a bounded candidate set using configured Reflex-backend probabilities.","parameters":{"type":"object","properties":{"state":{},"instructions":{"type":"string"},"items":{"type":"object","minProperties":2,"additionalProperties":{}},"contract":{"type":"string"}},"required":["state","instructions","items"]}}
NERVE_VERIFY={"name":"nerve_verify","description":"Verify an outcome as PASS, RETRY, REPLAN, or ESCALATE.","parameters":{"type":"object","properties":{"state":{},"instructions":{"type":"string"},"contract":{"type":"string"}},"required":["state","instructions"]}}
_INSTRUCTIONS={"description":"Required provider instruction context: string, object, or array.","oneOf":[{"type":"string"},{"type":"object"},{"type":"array"}]}
_CHOICE={"type":"object","properties":{"type":{"type":"string","enum":["choice"]},"instructions":_INSTRUCTIONS,"criteria":{"type":"object","minProperties":2,"additionalProperties":{}}},"required":["type","instructions","criteria"]}
_SCORE={"type":"object","properties":{"type":{"type":"string","enum":["score"]},"instructions":_INSTRUCTIONS,"criteria":{"type":"array","minItems":2,"items":{}}},"required":["type","instructions","criteria"]}
_NOUL_CRITERIA={"type":"object","description":"Optional NOUL outcome descriptions; when present, exactly true and false are required.","properties":{"true":_INSTRUCTIONS,"false":_INSTRUCTIONS},"required":["true","false"],"additionalProperties":False}
_NOUL={"type":"object","properties":{"type":{"type":"string","enum":["noul"]},"instructions":_INSTRUCTIONS,"criteria":_NOUL_CRITERIA},"required":["type","instructions"]}
NERVE_ASSESS={"name":"nerve_assess","description":"Ask up to 16 native typed questions over shared state through the configured Reflex backend.","parameters":{"type":"object","properties":{"state":{},"questions":{"type":"object","minProperties":1,"maxProperties":16,"additionalProperties":{"oneOf":[_CHOICE,_SCORE,_NOUL]}},"contract":{"type":"string"}},"required":["state","questions"]}}
NERVE_CONTEXT_CURATE={"name":"nerve_context_curate","description":"Reflex-assisted context-value planning with deterministic local retention policy.","parameters":{"type":"object","properties":{"goal":{"type":"string"},"items":{"type":"array","minItems":1,"maxItems":48,"items":{"type":"object","properties":{"id":{"type":"string"},"kind":{"type":"string"},"content":{"type":"string"},"recoverable":{"type":"boolean"},"pinned":{"type":"boolean"},"metadata":{"type":"object"}},"required":["id","content"]}},"preserve_tail":{"type":"integer","minimum":0,"maximum":12},"preview_chars":{"type":"integer","minimum":160,"maximum":4000},"anchor_chars":{"type":"integer","minimum":40,"maximum":1200},"stub_chars":{"type":"integer","minimum":40,"maximum":1200},"min_confidence":{"type":"number","minimum":0,"maximum":1},"mode":{"type":"string","enum":["apply","shadow"]},"policy":{"type":"object"},"contract":{"type":"string"}},"required":["goal","items"]}}
NERVE_CONTEXT_REHYDRATE={"name":"nerve_context_rehydrate","description":"Restore sanitized evidence from a local Jev anchor.","parameters":{"type":"object","properties":{"evidence_id":{"type":"string"},"contract":{"type":"string"}},"required":["evidence_id"]}}
NERVE_STATS={"name":"nerve_stats","description":"Return bounded local Nerve/Reflex telemetry.","parameters":{"type":"object","properties":{"section":{"type":"string","enum":["summary","receipts","gate","context","nervous","quality","outcomes","all"]},"recent_limit":{"type":"integer","minimum":0,"maximum":20},"include_recent":{"type":"boolean"}}}}
NERVE_NERVOUS_EVENT={"name":"nerve_nervous_event","description":"Emit one decision-significant event into the asynchronous Reflex nervous system.","parameters":{"type":"object","properties":{"type":{"type":"string"},"goal":{"type":"string"},"choices":{"type":"array","items":{"type":"string"}},"hermes_decision":{"type":"string"},"criteria":{"type":"object"},"state":{},"evidence":{},"strategy":{"type":"string"},"hypothesis":{"type":"string"},"materiality":{"type":"number","minimum":0,"maximum":1},"uncertainty":{"type":"number","minimum":0,"maximum":1},"novelty":{"type":"number","minimum":0,"maximum":1},"consequence":{"type":"number","minimum":0,"maximum":1},"risk":{"type":"number","minimum":0,"maximum":1},"reversible":{"type":"boolean"},"contradiction":{"type":"boolean"},"strategy_changed":{"type":"boolean"},"repeated_failure":{"type":"boolean"},"completion_candidate":{"type":"boolean"},"turn_id":{"type":"string"},"session_id":{"type":"string"},"state_version":{"type":"string"},"decision_version":{"type":"string"}},"required":["type","goal"]}}

_CRITERION={"type":"object","properties":{"id":{"type":"string"},"description":{"type":"string"},"required":{"type":"boolean"},"weight":{"type":"number","minimum":0},"estimated_tokens":{"type":"integer","minimum":0},"depends_on":{"type":"array","items":{"type":"string"}},"evidence_requirements":{"type":"array","items":{"type":"string"}}},"required":["id","description"]}
NERVE_SUPERVISE_CARD={"name":"nerve_supervise_card","description":"Bind/inspect/verify a structured Definition of Done and budget for one canonical Kanban card.","parameters":{"type":"object","properties":{"action":{"type":"string","enum":["bind","amend","bind_run","status","verify_criterion","record_usage","assess_trajectory","checkpoint","label_outcome","request_review"]},"task_id":{"type":"string"},"goal":{"type":"string"},"criteria":{"type":"array","items":_CRITERION},"reserve_tokens":{"type":"integer","minimum":0},"checkpoint_fractions":{"type":"array","items":{"type":"number","minimum":0,"maximum":1}},"actor":{"type":"string"},"run_id":{"type":"integer"},"contract_hash":{"type":"string"},"claim_identity":{"type":"string"},"worker_id":{"type":"string"},"criterion_id":{"type":"string"},"consumed_tokens":{"type":"integer","minimum":0},"source":{"type":"string"},"trigger":{"type":"string"},"failures":{"type":"array","items":{"type":"string"}},"decision_id":{"type":"string"},"reason":{"type":"string"},"current_plan":{"type":"string"},"test_summary":{"type":"string"},"artifacts":{"type":"array"},"workspace_result":{"type":"object"},"checkpoint_complete":{"type":"boolean"},"successful":{"type":"boolean"},"outcome":{"type":"string"},"summary":{"type":"string"},"reviewer":{"type":"string"}},"required":["action"]}}
NERVE_WORK_EVENT={"name":"nerve_work_event","description":"Emit a structured supervised-work checkpoint/progress event for the current exact Kanban run.","parameters":{"type":"object","properties":{"event_type":{"type":"string","enum":["CRITERION_STARTED","CRITERION_CLAIMED_PASS","CRITERION_FAILED","BLOCKER_FOUND","PLAN_CHANGED","ARTIFACT_CREATED","TEST_FAILED","TEST_PASSED","EVIDENCE_ADDED","CHECKPOINT_READY","HANDOFF_REQUESTED"]},"criterion_id":{"type":"string"},"payload":{"type":"object"},"event_id":{"type":"string"},"task_id":{"type":"string"},"run_id":{"type":"integer"},"contract_hash":{"type":"string"},"claim_identity":{"type":"string"}},"required":["event_type"]}}
NERVE_WORK_STATUS={"name":"nerve_work_status","description":"Inspect evidence-backed progress/frontier/control for a supervised Kanban card.","parameters":{"type":"object","properties":{"task_id":{"type":"string"}}}}
_REMOTE_COMMON={"job_id":{"type":"string"}}
NERVE_REMOTE_DELEGATE_TASK={"name":"nerve_remote_delegate_task","description":"Dispatch a durable task to an admin-configured SSH Hermes worker.","parameters":{"type":"object","properties":{"host":{"type":"string"},"goal":{"type":"string"},"context":{"type":"string"},"workspace":{"type":"string"},"profile":{"type":"string"},"max_turns":{"type":"integer","minimum":1},"task_id":{"type":"string"},"require_claim_fence":{"type":"boolean"}},"required":["host","goal"]}}
NERVE_REMOTE_WORKER_STATUS={"name":"nerve_remote_worker_status","description":"Read durable SSH worker status.","parameters":{"type":"object","properties":_REMOTE_COMMON,"required":["job_id"]}}
NERVE_REMOTE_WORKER_RESULT={"name":"nerve_remote_worker_result","description":"Read or briefly wait for a durable SSH worker result.","parameters":{"type":"object","properties":dict(_REMOTE_COMMON,wait_seconds={"type":"number","minimum":0,"maximum":120}),"required":["job_id"]}}
NERVE_REMOTE_WORKER_CANCEL={"name":"nerve_remote_worker_cancel","description":"Request cancellation of a durable SSH worker.","parameters":{"type":"object","properties":_REMOTE_COMMON,"required":["job_id"]}}
NERVE_REMOTE_WORKER_CONTROL={"name":"nerve_remote_worker_control","description":"Send WATCH/REPLAN/BLOCK/STOP_REQUESTED to a running SSH worker via a run-specific control file.","parameters":{"type":"object","properties":dict(_REMOTE_COMMON,control={"type":"string","enum":["WATCH","REPLAN","BLOCK","STOP_REQUESTED"]},decision_id={"type":"string"},reason={"type":"string"}),"required":["job_id","control"]}}
